'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
        Private Shared addedHandler As Boolean

        Private Shared addedHandlerLockObject As New Object

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
            If My.Application.SaveMySettingsOnExit Then
                My.Settings.Save()
            End If
        End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
                   If Not addedHandler Then
                        SyncLock addedHandlerLockObject
                            If Not addedHandler Then
                                AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                                addedHandler = True
                            End If
                        End SyncLock
                    End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")> _
        Public Property WindowPosition() As Global.System.Drawing.Point
            Get
                Return CType(Me("WindowPosition"), Global.System.Drawing.Point)
            End Get
            Set(ByVal value As Global.System.Drawing.Point)
                Me("WindowPosition") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("349, 505")> _
        Public Property WindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("WindowSize"), Global.System.Drawing.Size)
            End Get
            Set(ByVal value As Global.System.Drawing.Size)
                Me("WindowSize") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property WindowState() As String
            Get
                Return CType(Me("WindowState"), String)
            End Get
            Set(ByVal value As String)
                Me("WindowState") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property Activated() As Boolean
            Get
                Return CType(Me("Activated"), Boolean)
            End Get
            Set(ByVal value As Boolean)
                Me("Activated") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property ActivationNo() As Integer
            Get
                Return CType(Me("ActivationNo"), Integer)
            End Get
            Set(ByVal value As Integer)
                Me("ActivationNo") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property OpenCount() As Integer
            Get
                Return CType(Me("OpenCount"), Integer)
            End Get
            Set(ByVal value As Integer)
                Me("OpenCount") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property RegistrationCode() As String
            Get
                Return CType(Me("RegistrationCode"), String)
            End Get
            Set(ByVal value As String)
                Me("RegistrationCode") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property InstallDate() As String
            Get
                Return CType(Me("InstallDate"), String)
            End Get
            Set(ByVal value As String)
                Me("InstallDate") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property Period() As String
            Get
                Return CType(Me("Period"), String)
            End Get
            Set(ByVal value As String)
                Me("Period") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property BackupDate() As String
            Get
                Return CType(Me("BackupDate"), String)
            End Get
            Set(ByVal value As String)
                Me("BackupDate") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property BackupRemindDate() As String
            Get
                Return CType(Me("BackupRemindDate"), String)
            End Get
            Set(ByVal value As String)
                Me("BackupRemindDate") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property SalariumConnectionString() As String
            Get
                Return CType(Me("SalariumConnectionString"), String)
            End Get
            Set(ByVal value As String)
                Me("SalariumConnectionString") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property SalariumDate() As String
            Get
                Return CType(Me("SalariumDate"), String)
            End Get
            Set(ByVal value As String)
                Me("SalariumDate") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property StartWithLastOpenedCompany() As Boolean
            Get
                Return CType(Me("StartWithLastOpenedCompany"), Boolean)
            End Get
            Set(ByVal value As Boolean)
                Me("StartWithLastOpenedCompany") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property FinancialPeriod() As String
            Get
                Return CType(Me("FinancialPeriod"), String)
            End Get
            Set(ByVal value As String)
                Me("FinancialPeriod") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property IPAddress() As String
            Get
                Return CType(Me("IPAddress"), String)
            End Get
            Set(ByVal value As String)
                Me("IPAddress") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property LastOpenedCompany() As String
            Get
                Return CType(Me("LastOpenedCompany"), String)
            End Get
            Set(ByVal value As String)
                Me("LastOpenedCompany") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property LastOpenedCompanyID() As String
            Get
                Return CType(Me("LastOpenedCompanyID"), String)
            End Get
            Set(ByVal value As String)
                Me("LastOpenedCompanyID") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property SystemDate() As String
            Get
                Return CType(Me("SystemDate"), String)
            End Get
            Set(ByVal value As String)
                Me("SystemDate") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Open")> _
        Public Property SetupGuide() As String
            Get
                Return CType(Me("SetupGuide"), String)
            End Get
            Set(ByVal value As String)
                Me("SetupGuide") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Open")> _
        Public Property ObsolescenceInfo() As String
            Get
                Return CType(Me("ObsolescenceInfo"), String)
            End Get
            Set(ByVal value As String)
                Me("ObsolescenceInfo") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Periodic")> _
        Public Property DefaultPage() As String
            Get
                Return CType(Me("DefaultPage"), String)
            End Get
            Set(ByVal value As String)
                Me("DefaultPage") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("Periodic")> _
        Public Property CompanyDefaultPage() As String
            Get
                Return CType(Me("CompanyDefaultPage"), String)
            End Get
            Set(ByVal value As String)
                Me("CompanyDefaultPage") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property ChatName() As String
            Get
                Return CType(Me("ChatName"), String)
            End Get
            Set(ByVal value As String)
                Me("ChatName") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Salarium.My.MySettings
            Get
                Return Global.Salarium.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
